// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[] = SECRET_SSID;          // Network SSID (name)
const char PASS[] = SECRET_OPTIONAL_PASS; // Network password (use for WPA, or
                                          // use as key for WEP)

void onBocchiDataChange();
void onDashboardDataChange();

String bocchi_data;
String dashboard_data;
int peoplecount;

void initProperties() {

  ArduinoCloud.addProperty(bocchi_data, READWRITE, ON_CHANGE,
                           onBocchiDataChange);
  ArduinoCloud.addProperty(dashboard_data, READWRITE, ON_CHANGE,
                           onDashboardDataChange);
  ArduinoCloud.addProperty(peoplecount, READ, ON_CHANGE, NULL);
}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
